### ISSUE TITLE
Create MCQA for Array.push()

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#1]
Please create an MCQ to be added as question number 19.

The multiple choice question should be on the topic `.push()` method of an array. The difficulty level should be "Medium/Hard"

**What is `Array.push()` method?**
The `push()` method add items at end of an array and returns length.

- [ ] add your code to 019 folder under code
- [ ] add your question to 19 in README.md file
- [ ] create a video explanation (optional)

**Comment by Subham5401** [comment]
Hi,
I'd like to take this further.
