### ISSUE TITLE
Create MCQA for Array.reduceRight() method 

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#10]
Please create an MCQA to be added as question number 28.

The multiple choice question should be on the topic `.reduceRight()` method of an array. The difficulty level should be "Medium/Hard"

**Tasks**: 
- [ ] add your code to 028 folder under code
- [ ] add your question to 28 in README.md file
- [ ] create a video explanation (optional)

**Sample interview question for inspiration**
- What is the difference between `reduce()` and `reduceRight()`?
	- `reduceRight()` loops from right to left

**Comment by Subham5401** [comment]
Plz assign to me.
