### ISSUE TITLE
Create MCQA for Array.sort() method

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#14]
Please create an MCQA to be added as question number 29.

The multiple choice question should be on the topic `.sort()` method of an array. The difficulty level should be "Medium/Hard"

**Tasks**: 
- [ ] add your code to 029 folder under code
- [ ] add your question to 29 in README.md file
- [ ] create a video explanation and upload on YouTube (optional)

**Explanation:**
- `arr.sort()`: sorts alphabetically when arr is of strings
- This modifies the original array
- To do numeric sort: use comparison method in callback function inside sort
- if no callback fn is given then it will sort the unicode string value

**Sample interview question for inspiration**
- What will be the output of `["bgwebagency", 1, 2, 3, 4, undefined, 11, 9, 1000, "apple", undefined].sort()`?
	- ans: `[1, 1000, 11, 2, 3, 4, 9, 'apple', 'bgwebagency', undefined, undefined]`
	- all `undefined` values are moved to the end
- How will you sort an object literal?
        - ans: by using a callback function
- How will you sort a numeric array?
- Sort all values of array in descending order.

**Comment by murat114** [comment]
Hello, 
I would like to take on the task.

**Comment by kirandash** [comment]
> Hello, 
> 
> I would like to take on the task.

Awesome! Thanks for showing your interest @murat114. I have now assigned the task to you. 

If you need any help, you can comment here or reach me on discord at: 

https://discord.gg/62VR3MMCVm

**Comment by murat114** [comment]
Thank you to assign me the task 👍

**Comment by kirandash** [comment]
Hi @murat114, I just noticed that there is already a PR for this issue at https://github.com/bgwebagency/who-wants-to-be-a-javascriptaire/pull/20 by another user although this issue was not assigned to them.

Is it ok if you pick any issue other than #20 and #7 since there are PRs for these two issues.

But if you have already started working on it then I will not use their PRs.  Since you are assigned to this task

**Comment by murat114** [comment]
Hi @kirandash, I have already started the work and wanted to finish it by next week at the latest. But if there is no other way I could start the task Create MCQA for Date() class #16.

**Comment by kirandash** [comment]
> Hi @kirandash, I have already started the work and wanted to finish it by next week at the latest. But if there is no other way I could start the task Create MCQA for Date() class #16. That would not be a problem for me.

If you have not finished working on this, I think it will be better if you can work on #16. Please comment there so that I can assign you.
Thanks a lot for understanding! Since there's another PR for this task already, I don't want their effort to be wasted.

**Comment by murat114** [comment]
You are welcome @kirandash

**Comment by kirandash** [comment]
Thanks @Vida-1 for working on this. Much appreciated!
