### ISSUE TITLE
Create MCQA for destructuring array topic

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#15]
Please create an MCQA to be added as question number 30.

The multiple choice question should be on the topic "destructuring an array". The difficulty level should be "Medium/Hard"

**Tasks**: 
- [ ] add your code to 030 folder under code
- [ ] add your question to 30 in README.md file
- [ ] create a video explanation and upload on YouTube (optional)

**Explanation:**
- getting values from arr or obj into individual variables
  - ex: `let [a3, b3, c3 = 5] = arr1;`
- You can swap values using destructuring.
   - `[a1, b1] = [b1, a1];`

**Sample interview question for inspiration**
- What will be the output of this code?
```
let [a,b,c] = [5,,7];
console.log(a,b,c);
```
ans: `5 undefined 7`

**Comment by KNO29** [comment]
Hello,
I would like to do this issue.

**Comment by kirandash** [comment]
Thanks @KNO29 🙏 for showing your interest! I have now assigned the task to you.

If you need any help, you can comment here or reach me on discord at:

https://discord.gg/62VR3MMCVm

And if you like this project, please do show your support by leaving a star ⭐️ for more visibility

**Comment by kirandash** [comment]
Thanks for your contribution @KNO29!

Your PR was perfect. To the point :)
