### ISSUE TITLE
Create MCQA for Date() class

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#16]
Please create an MCQA to be added as question number 31.

The multiple choice question should be on the topic "Date()" class. The difficulty level should be "Medium/Hard"

**Tasks**: 
- [ ] add your code to 031 folder under code
- [ ] add your question to 31 in README.md file
- [ ] create a video explanation and upload on YouTube (optional)

**Explanation:**
There are 4 ways to create date object
- `new Date()`: current date and time along with local tz
- `new Date(year, month, day, hours, minutes, seconds, milliseconds)`: more preferable way to deal with dates
- `new Date(milliseconds)`: milliseconds from 01 Jan 1970
- `new Date("year-month-dayTH:M:SECZ")`: if T and Z are not given then value might vary from browser to browser (T: Time, Z: zone)
- ISO 8601 Extended date format: `YYYY-MM-DDTHH:mm:ss.sssZ`

**Sample interview question for inspiration**
- What will be the output of this code? Assuming user's timezone is set to GMT+0800 (Singapore Standard Time)
```
const date1 = new Date("2023-11-23T08:01:01.11+04:00")
const date2 = new Date("2023-11-23T08:01:01.11Z")
const date3 = new Date("2023-11-23T08:01:01.11")
console.log(date1, date2, date3);
```
ans: Thu Nov 23 2023 12:01:01 GMT+0800 (Singapore Standard Time) Thu Nov 23 2023 16:01:01 GMT+0800 (Singapore Standard Time) Thu Nov 23 2023 08:01:01 GMT+0800 (Singapore Standard Time)

**Comment by murat114** [comment]
Hello,
I would like to take on the task.

**Comment by kirandash** [comment]
> Hello, I would like to take on the task.

Thanks! I have now assigned the task to you.

If you need any help, you can comment here or reach me on discord at:

https://discord.gg/62VR3MMCVm

**Comment by kirandash** [comment]
Thanks a lot @murat114 for your contribution! 🙏 Much appreciated :)

Happy coding!
