### ISSUE TITLE
Create MCQA for Array.unshift() 

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#2]
Please create an MCQ to be added as question number 20.

The multiple choice question should be on the topic `.unshift()` method of an array. The difficulty level should be "Medium/Hard"

**What is `Array.unshift()` method?**
The `unshift()` method add items at beginning, returns length

- [ ] add your code to 020 folder under code
- [ ] add your question to 20 in README.md file
- [ ] create a video explanation (optional)

**Comment by Subham5401** [comment]
Hi,
I'd like to take this further.
