### ISSUE TITLE
Create MCQA for `this` Object

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#25]
Please create an MCQA to be added as question number 35.

The multiple choice question should be on the topic "this object". The difficulty level should be "Easy/Medium"

**Tasks**: 
- [ ] add your code to 035 folder under code
- [ ] add your question to 35 in README.md file
- [ ] create a video explanation and upload on YouTube (optional)

**Explanation:**
- `this` contains the current context
- in browser: `this` will always return `window` context unless it is wrapped in an object or wrapper
- `this` doesn't work with arrow fn. Since with ES6: this was removed from arrow fn and added to `class`. In arrow function, `this` will point to `window`

**Comment by MehmetTerc** [comment]
i can take that

**Comment by RahulRana701** [comment]
@kirandash I would like to work on that can you assign it to me..

**Comment by kirandash** [comment]
> @kirandash I would like to work on that can you assign it to me..

Hi @RahulRana701 Thanks a lot for showing your request! 🙏

But since @MehmetTerc had commented before, I would be assigning this task to him. But there are other open issues on this repo. Feel free to comment on any one of them.

**Comment by kirandash** [comment]
Thanks @JP-GECT for your contribution.
