### ISSUE TITLE
Create MCQA for `call()`, `apply()` and `bind()`

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#26]
Please create an MCQA to be added as question number 36.

The multiple choice question should be on the topic "call, apply and bind". The difficulty level should be "Medium/Hard"

**Tasks**: 
- [ ] add your code to 036 folder under code
- [ ] add your question to 36 in README.md file
- [ ] create a video explanation and upload on YouTube (optional)

**Explanation:**
- `call`, `apply` and `bind` changes context of a function
- `call` and `apply` executes fn immediately while `bind` returns a fn
- Note: we can not assign object to `this` operator directly in JS. that's why we have to use `call`, `apply` or `bind` method
- Practical applications of `call`, `apply` and `bind`:
   - chain constructors for an object
   - function borrowing, Ex: borrow filter fn from array prototype for arguments

**Comment by RahulRana701** [comment]
hi @kirandash I would like to work on that please assign it to me..

**Comment by kirandash** [comment]
> hi @kirandash I would like to work on that please assign it to me..

Thanks @RahulRana701  🙏 for showing your interest! I have now assigned the task to you.

If you need any help, you can comment here or reach me on discord at:

https://discord.gg/62VR3MMCVm

And if you like this project, please do show your support by leaving a star ⭐️ for more visibility

**Comment by kirandash** [comment]
Thanks for your contribution @RahulRana701 🙏
