### ISSUE TITLE
Create MCQA for Array. pop() 

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#3]
Please create an MCQ to be added as question number 21.

The multiple choice question should be on the topic `.pop()` method of an array. The difficulty level should be "Medium/Hard"

**What is `Array.pop()` method?**
The `pop()` method removes last item and returns removed element

- [ ] add your code to 021 folder under code
- [ ] add your question to 21 in README.md file
- [ ] create a video explanation (optional)

**Comment by Subham5401** [comment]
Hi,
I'd like to take this further.
