### ISSUE TITLE
Create MCQA for Inheritance, Subclassing and Extending built in class 

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#31]
Please create an MCQA to be added as question number 38.

The multiple choice question should be on the topic "Inheritance, Subclassing and Extending built in class". The difficulty level should be "Medium/Hard"

**Tasks**: 
- [ ] add your code to 038 folder under code
- [ ] add your question to 38 in README.md file
- [ ] create a video explanation and upload on YouTube (optional)

**Explanation:**
- In `ES6`, extends keyword can be used for extending class. ES5 had other ways of extending class

**Sample interview question for inspiration**
- How can you inherit a class?
- What is subclassing?
- What is the purpose of `super` keyword?
   - ans: `super` keyword is used to call parent constructor, method or properties. `super()`; `super.prop`; `super.method()`
- How will you override a method?
   - ans: use same name as method in parent. It will override in child. To call specifically parent method: use `super.methodName()`
- How can you extend a built-in class?

**Comment by RahulRana701** [comment]
@kirandash  I would like to work on this issue , please assign it to me ..

**Comment by kirandash** [comment]
@rahulrana701 any update on this?

**Comment by rahulrana701** [comment]
hi @kirandash here is the link of the pr for this issue , sorry for the late response https://github.com/bgwebagency/who-wants-to-be-a-javascriptaire/pull/53#issue-1750432370

**Comment by kirandash** [comment]
Thanks for your contribution @rahulrana701
