### ISSUE TITLE
Create MCQA for Destructuring Object Literal

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#32]
Please create an MCQA to be added as question number 39.

The multiple choice question should be on the topic "Destructuring Object Literal". The difficulty level should be "Easy/Medium"

**Tasks**: 
- [ ] add your code to 039 folder under code
- [ ] add your question to 39 in README.md file
- [ ] create a video explanation and upload on YouTube (optional)

**Comment by kirandash** [comment]
@rahulrana701 any update on this?

**Comment by rahulrana701** [comment]
hi @kirandash here is the link of the pr for this issue , sorry for the late response https://github.com/bgwebagency/who-wants-to-be-a-javascriptaire/pull/54#issue-1750444876

**Comment by rahulrana701** [comment]
hi @kirandash  created a new pr you can check it out. https://github.com/bgwebagency/who-wants-to-be-a-javascriptaire/pull/55#issue-1750850601
