### ISSUE TITLE
Create MCQA for topic Named Import and Export

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#39]
Please create an MCQA to be added as question number 41.

The multiple choice question should be on the topic "Named Import and Export". The difficulty level should be "Easy/Medium/Hard"

**Tasks**: 
- [ ] add your code to 041 folder under code
- [ ] add your question to 41 in README.md file

**Explanation:**
- There are two types of import export syntax:
   - default
   - named
- `import * as obj from filename`: To import all modules under one name (not a good practice). 
    - In build tools like webpack, unwanted modules are removed internally i.e. Treeshaking
- `import { sum as mySum } from filename`
- `import sum from filename`
- `export sum as total from filename`
- `export { sum, diff } from filename`

**Sample interview question for inspiration**
- What is a named export and import ?
- Can you avoid `{}` while importing a named module ?
   - No
- How can you import all named modules from a file ?
- Is it a good practice to import all modules together ?
- Do the modules hoist ?
   - Yes
- Do you need the same name while importing a named module or you can change ?
   - can change with `as` keyword

**Comment by KNO29** [comment]
Hello,
I would like to do this issue.
