### ISSUE TITLE
Create MCQA for Array.shift()

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#4]
Please create an MCQ to be added as question number 22.

The multiple choice question should be on the topic `.shift()` method of an array. The difficulty level should be "Medium/Hard"

**What is `Array.shift()` method?**
The `shift()` method add items at beginning, returns length

- [ ] add your code to 022 folder under code
- [ ] add your question to 22 in README.md file
- [ ] create a video explanation (optional)

**Comment by Subham5401** [comment]
Hi,
I'd like to take this further.
