### ISSUE TITLE
Create MCQA for Array.splice()

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#5]
Please create an MCQ to be added as question number 23.

The multiple choice question should be on the topic `.splice()` method of an array. The difficulty level should be "Medium/Hard"

**What is `Array.splice()` method?**
The `splice(startIdx)`: delete starting from `startIdx` and returns deleted items from array
This method can be used to add, remove, insert or replace an item by modifying the technique. 
Ex: `arr.splice(2, 0, "New"))` will insert "New" at index 2 and delete 0 items.
`arr.splice(2, 1))` will remove one item starting from index 2.

- [ ] add your code to 023 folder under code
- [ ] add your question to 23 in README.md file
- [ ] create a video explanation (optional)

**Comment by Subham5401** [comment]
Hi,
I am interested in taking this further.

**Comment by kirandash** [comment]
Hi @Subham5401 Thanks for showing your interest. I have assigned the task to you. Feel free to let me know if you have any questions. You can comment here or also reach me on discord at https://discord.gg/62VR3MMCVm

**Comment by Subham5401** [comment]
I will take the other issues as well. Please let me know if I commit everything in a single PR?

**Comment by kirandash** [comment]
@Subham5401 yes you can commit the other issues in a single PR. But please request for assignment on individual issues. 
So I can assign them to you.

**Comment by Subham5401** [comment]
@kirandash sure, thanks!
