### ISSUE TITLE
Create MCQA for basic array search methods: Array.indexOf(), Array.lastIndexOf(), Array.includes()

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#6]
Please create an MCQA to be added as question number 24.

The multiple choice question should be on the topic basic array search methods: `.indexOf()`, `.lastIndexOf()` and `.includes()` method of an array. The difficulty level should be "Medium/Hard"

**Tasks**: 
- [ ] add your code to 024 folder under code
- [ ] add your question to 24 in README.md file
- [ ] create a video explanation (optional)

**I have added some explanation for these methods below in case you don't remebmer**
- `indexOf()`: arr.indexOf(searchElem, startIndex): 
	- returns index where search items is found. -1 if not found
	- returns index of first element if multiple items found
- `lastIndexOf()`:
	- same but returns index of last element if multiple items found
- `includes()`:
	- same but returns true or false
	
**Sample Questions**
1. What will be the output of this code ?
```
	let arr=["One","Two","Three","Four","Five"];
	console.log(arr.lastIndexOf("Abcd")); // -1
```
2. What is the difference between `indexOf()` and `includes()` method ?
Ans: `indexOf()` returns index while `includes()` returns boolean

These questions are easy, feel free to make it bit more challenging.

**Comment by Subham5401** [comment]
Hi,
Plz assign this to me.

**Comment by Subham5401** [comment]
Do all three concepts necessarily have to be in the question?

**Comment by kirandash** [comment]
@Subham5401 Thanks for your interest. I thought keeping all three question will be a quick way to cover all three methods. Since they are not that difficult and similar to each other.

You can maybe create an array ex:  `const arr = [1,2,3,4,4,3,5,6,7]`
and check `console.log(arr.indexOf(2), arr.lastIndexOf(3), arr.includes(9)`

output will be `1 5 false`

**Comment by Subham5401** [comment]
Thanks for the explaination @kirandash!
