### ISSUE TITLE
Create MCQA for advanced array search methods: Array.find(), Array.findIndex(), Array.filter()

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#7]
Please create an MCQA to be added as question number 25.

The multiple choice question should be on the topic advanced array search methods: `.find()`, `.findIndex()` and `.filter()` method of an array. The difficulty level should be "Medium/Hard"

**Tasks**: 
- [ ] add your code to 025 folder under code
- [ ] add your question to 25 in README.md file
- [ ] create a video explanation (optional)

**I have added some explanation for these methods below in case you don't remebmer**
- `find()`: returns item which matches the callback condition. It only returns first match
- `filter()`: returns array of items that matches the condition
	
**Sample Questions for inspiration**
1. What is the difference between `find()` and `filter()` method ?
- `find` returns item while `filter` returns array of all items
2. If there is no value to return, what will `findIndex()` return ?
- `undefined`
3. How will you search multiple values in an array?
- `filter`

These questions are easy, feel free to make it bit more challenging. Except the second one. Because most developers reply `-1` as the answer to it

**Comment by jwernethUMD** [comment]
Hi, could you please assign me to this issue?

**Comment by kirandash** [comment]
> Hi, could you please assign me to this issue?

Awesome! Thanks for showing your interest @jwernethUMD. I have now assigned the task to you.

If you need any help, you can comment here or reach me on discord at:

https://discord.gg/62VR3MMCVm

**Comment by kirandash** [comment]
Thanks for your contribution @jwernethUMD!

Much appreciated :)
