### ISSUE TITLE
Create MCQA for Array.map() method

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#8]
Please create an MCQA to be added as question number 26.

The multiple choice question should be on the topic `.map()` method of an array. The difficulty level should be "Easy/Medium/Hard"

**Tasks**: 
- [ ] add your code to 026 folder under code
- [ ] add your question to 26 in README.md file
- [ ] create a video explanation (optional)

**I have added some explanation for these methods below in case you don't remebmer**
- The `map()` method returns new array after modifying each item in array

**Comment by Subham5401** [comment]
!assign
