### ISSUE TITLE
Create MCQA for Array.reduce() method

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/who-wants-to-be-a-javascriptaire#9]
Please create an MCQA to be added as question number 27.

The multiple choice question should be on the topic `.reduce()` method of an array. The difficulty level should be "Medium/Hard"

**Tasks**: 
- [ ] add your code to 027 folder under code
- [ ] add your question to 27 in README.md file
- [ ] create a video explanation (optional)

**Sample interview question for inspiration**
- How to flatten a 2D array using `reduce()`?
	`const flatArr = twoDimArr.reduce((acc, item) => acc.concat(item));`

**Comment by Subham5401** [comment]
Plz assign to me.
